// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoloiridonikoqzlreas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbG9pcmlkb25pa29xemxyZWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMDEyMTEsImV4cCI6MjA5MDc3NzIxMX0.roxb6dZir6vpP2ATkw-LErYBW0uMqpX3rPTqDMhcv-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});